/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author Wasee-Ur-Rehman CH
 */
import javax.swing.ButtonGroup;

public class Glance extends javax.swing.JFrame {

    String cityName = "";
    String stateCode = "";
    String countryCode = "";
    String longitude = "";
    String latitude = "";
    
    /**
     * Creates new form Glance
     */
    public Glance() {
        initComponents();
        myinitcomponents();
    }
    private void myinitcomponents()
    {
     ButtonGroup buttonGroup = new ButtonGroup();

    // Add radio buttons to the ButtonGroup
    buttonGroup.add(ByCity);
    buttonGroup.add(ByCoordinates);
    
     LatitudeInput.setVisible(false);
    LongitudeInput.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Option = new javax.swing.JLabel();
        ByCity = new javax.swing.JRadioButton();
        ByCoordinates = new javax.swing.JRadioButton();
        CityLabel = new javax.swing.JLabel();
        StateCodeLabel = new javax.swing.JLabel();
        CountryCodeLabel = new javax.swing.JLabel();
        CityInput = new javax.swing.JTextField();
        CountryCodeInput = new javax.swing.JTextField();
        StateCodeInput = new javax.swing.JTextField();
        Searchbtn = new javax.swing.JButton();
        LongitudeInput = new javax.swing.JTextField();
        LatitudeInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glance Weather App");
        setResizable(false);

        Title.setFont(new java.awt.Font("Segoe UI Historic", 1, 30)); // NOI18N
        Title.setText("AT Glance Weather Application");

        Option.setText("Select Option");

        ByCity.setText("Search by City Name, State Code and Country Code");
        ByCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByCityActionPerformed(evt);
            }
        });

        ByCoordinates.setText("Search by Lattitude and Longitude");
        ByCoordinates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ByCoordinatesActionPerformed(evt);
            }
        });

        CityLabel.setText("Enter City Name:");
        CityLabel.setFocusCycleRoot(true);

        StateCodeLabel.setText("Enter State Code:");
        StateCodeLabel.setFocusCycleRoot(true);

        CountryCodeLabel.setText("Enter Country Code:");
        CountryCodeLabel.setFocusCycleRoot(true);

        CityInput.setFocusCycleRoot(true);
        CityInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CityInputMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CityInputMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CityInputMouseReleased(evt);
            }
        });
        CityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityInputActionPerformed(evt);
            }
        });

        CountryCodeInput.setFocusCycleRoot(true);
        CountryCodeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryCodeInputActionPerformed(evt);
            }
        });

        StateCodeInput.setFocusCycleRoot(true);
        StateCodeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateCodeInputActionPerformed(evt);
            }
        });

        Searchbtn.setText("Search");
        Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbtnActionPerformed(evt);
            }
        });

        LongitudeInput.setFocusCycleRoot(true);
        LongitudeInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LongitudeInputMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LongitudeInputMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LongitudeInputMouseReleased(evt);
            }
        });
        LongitudeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LongitudeInputActionPerformed(evt);
            }
        });

        LatitudeInput.setFocusCycleRoot(true);
        LatitudeInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LatitudeInputMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LatitudeInputMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LatitudeInputMouseReleased(evt);
            }
        });
        LatitudeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatitudeInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Option))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ByCoordinates)
                            .addComponent(ByCity)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CountryCodeLabel)
                            .addComponent(StateCodeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StateCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LongitudeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LatitudeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CountryCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title)
                    .addComponent(Searchbtn))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Option)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ByCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ByCoordinates)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLabel)
                    .addComponent(CityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LatitudeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StateCodeLabel)
                    .addComponent(StateCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LongitudeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountryCodeLabel)
                    .addComponent(CountryCodeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Searchbtn)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ByCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByCityActionPerformed
        // TODO add your handling code here:
    CityLabel.setText("Enter City Name:");
    CityLabel.setVisible(true);
    CityInput.setVisible(true);
    StateCodeLabel.setText("Enter State Code:");
    StateCodeLabel.setVisible(true);
    StateCodeInput.setVisible(true);
    CountryCodeLabel.setText("Enter Country Code:");
    CountryCodeLabel.setVisible(true);
    CountryCodeInput.setVisible(true);
    // Hide latitude and longitude inputs
    LatitudeInput.setVisible(false);
    LongitudeInput.setVisible(false);
    }//GEN-LAST:event_ByCityActionPerformed

    private void ByCoordinatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ByCoordinatesActionPerformed
        // TODO add your handling code here:
   CityLabel.setText("Enter Latitude:");
    CityLabel.setVisible(true);
    LatitudeInput.setVisible(true);
    StateCodeLabel.setText("Enter Longitude:");
    StateCodeLabel.setVisible(true);
    LongitudeInput.setVisible(true);
    // Hide city, state code, and country code inputs
    CityInput.setVisible(false);
    StateCodeInput.setVisible(false);
    CountryCodeInput.setVisible(false);
    CountryCodeLabel.setVisible(false);
    }//GEN-LAST:event_ByCoordinatesActionPerformed

    private void CityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityInputActionPerformed
        cityName= CityInput.getText();
        System.out.println(cityName);
    }//GEN-LAST:event_CityInputActionPerformed

    private void StateCodeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateCodeInputActionPerformed
     stateCode=StateCodeInput.getText();
    }//GEN-LAST:event_StateCodeInputActionPerformed

    private void SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbtnActionPerformed
        // TODO add your handling code here:
        
        WeatherInfoWindow weatherInfoWindow = new WeatherInfoWindow(cityName, stateCode, countryCode, latitude, longitude);
        weatherInfoWindow.setVisible(true);
    }//GEN-LAST:event_SearchbtnActionPerformed

    private void CountryCodeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryCodeInputActionPerformed
        countryCode=CountryCodeInput.getText();
    }//GEN-LAST:event_CountryCodeInputActionPerformed

    private void CityInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CityInputMouseExited

    }//GEN-LAST:event_CityInputMouseExited

    private void CityInputMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CityInputMouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CityInputMouseReleased

    private void CityInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CityInputMouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_CityInputMouseClicked

    private void LongitudeInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LongitudeInputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeInputMouseClicked

    private void LongitudeInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LongitudeInputMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeInputMouseExited

    private void LongitudeInputMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LongitudeInputMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_LongitudeInputMouseReleased

    private void LongitudeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LongitudeInputActionPerformed
        // TODO add your handling code here:
        longitude= LongitudeInput.getText();
    }//GEN-LAST:event_LongitudeInputActionPerformed

    private void LatitudeInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LatitudeInputMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LatitudeInputMouseClicked

    private void LatitudeInputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LatitudeInputMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_LatitudeInputMouseExited

    private void LatitudeInputMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LatitudeInputMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_LatitudeInputMouseReleased

    private void LatitudeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatitudeInputActionPerformed
        // TODO add your handling code here:
        latitude=LatitudeInput.getText();
    }//GEN-LAST:event_LatitudeInputActionPerformed

     public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    // Getter and setter methods for stateCode
    public String getStateCode() {
        return stateCode;
    }

    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }

    // Getter and setter methods for countryCode
    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    // Getter and setter methods for latitude
    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    // Getter and setter methods for longitude
    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Glance().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ByCity;
    private javax.swing.JRadioButton ByCoordinates;
    private javax.swing.JTextField CityInput;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JTextField CountryCodeInput;
    private javax.swing.JLabel CountryCodeLabel;
    private javax.swing.JTextField LatitudeInput;
    private javax.swing.JTextField LongitudeInput;
    private javax.swing.JLabel Option;
    private javax.swing.JButton Searchbtn;
    private javax.swing.JTextField StateCodeInput;
    private javax.swing.JLabel StateCodeLabel;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
